### PR TITLE
Userbar component.

### PR DESCRIPTION
**Pull request by GalKJ**
Building userbar component. Adding avatar, username, badge level and back navigation.

### CODE REVIEW

**Comment by GalKJ** [comment]
@Jbarget 

Hi Justen, We're hitting an issue with useHistory(). 

image

Just started looking into it ourselves but wondered if you've experience using this feature in React-router-dom?

Many thanks

**Comment by GalKJ** [comment]
@LauraK0 

Hi

**Comment by GalKJ** [comment]
@Jbarget 

Hello again, We've found a fix and it is that we're going to use `next/router` instead.

✨

**Comment by LauraK0** [comment]
Hi @Jbarget  

I keep getting an error from vercel when building the preview deployment with this branch. The error is when it tries to build the dynamic paths but I don't have this issue when running the code locally. I assume it has something to do with trying to build without getting all the data back from the supabase database?

Would you know how to resolve this issue? 

Also my code seems quite messy, if you had some ideas for refactoring that'd be awesome too.

Many thanks!
Laura

**Comment by LauraK0** [comment]
Hi @Jbarget, I think this is working now but if you had any ideas on refactoring that'd still be grand

**Review by DominicSimpson — APPROVED** [review]

**Pull request merged**
